# Uncomment the next line to define a global platform for your project
# platform :ios,'10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'accountBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod'Alamofire','~>4.7'
  pod'SwiftyJSON'
  # Pods for accountBook

end
