# Generated by Django 4.2.2 on 2023-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=125, verbose_name="디바이스ID")),
                (
                    "living_expenses",
                    models.IntegerField(default=0, verbose_name="생활비 예산"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="recipt",
            old_name="devceId",
            new_name="device_id",
        ),
        migrations.AlterField(
            model_name="recipt",
            name="date",
            field=models.DateField(null=True, verbose_name="결제일"),
        ),
    ]
