# Generated by Django 4.2.2 on 2023-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipt", "0002_budget_rename_devceid_recipt_device_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="device_id",
            field=models.CharField(max_length=125, unique=True, verbose_name="디바이스ID"),
        ),
    ]
