# Generated by Django 4.2.2 on 2023-06-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipt", "0003_alter_budget_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipt",
            name="list",
        ),
        migrations.AlterField(
            model_name="recipt",
            name="device_id",
            field=models.IntegerField(verbose_name="디바이스ID"),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=24, verbose_name="상품명")),
                ("amount", models.IntegerField(null=True)),
                ("price", models.IntegerField(null=True)),
                (
                    "recipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list",
                        to="recipt.recipt",
                    ),
                ),
            ],
        ),
    ]
