# Generated by Django 4.2.2 on 2023-06-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipt", "0005_remove_recipt_date_recipt_month_recipt_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipt",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipt.category",
                verbose_name="카테고리",
            ),
        ),
    ]
